# 🚇 CLOUDFLARED ELITE CONFIG - AUDITORIA
# Configuración profesional para túneles seguros

tunnel: auditoria-tunnel
credentials-file: ~/.cloudflared/a9ff5678-3610-48de-aa3e-6793f6240029.json

# 🌐 Ingress Rules Elite
ingress:
  # Auditoria Principal
  - hostname: auditoria.fascinantedigital.com
    service: http://localhost:3000
    originRequest:
      httpHostHeader: auditoria.fascinantedigital.com
      noTLSVerify: false
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 90s

  # API Gateway
  - hostname: api.auditoria.fascinantedigital.com
    service: http://localhost:3001
    originRequest:
      httpHostHeader: api.auditoria.fascinantedigital.com
      noTLSVerify: false

  # Tools Dashboard
  - hostname: tools.auditoria.fascinantedigital.com
    service: http://localhost:3002
    originRequest:
      httpHostHeader: tools.auditoria.fascinantedigital.com
      noTLSVerify: false

  # Analytics Dashboard
  - hostname: analytics.auditoria.fascinantedigital.com
    service: http://localhost:3003
    originRequest:
      httpHostHeader: analytics.auditoria.fascinantedigital.com
      noTLSVerify: false

  # Catch-all rule (debe ir al final)
  - service: http_status:404

# 🔧 Configuración Avanzada
originRequest:
  # Configuración de conexión
  connectTimeout: 30s
  tlsTimeout: 10s
  tcpKeepAlive: 30s
  keepAliveConnections: 10
  keepAliveTimeout: 90s
  
  # Headers personalizados
  httpHostHeader: auditoria.fascinantedigital.com
  
  # Configuración de proxy
  noTLSVerify: false
  disableChunkedEncoding: false
  
  # Configuración de buffer
  bufferSize: 65536

# 📊 Métricas y Logging
metrics: 127.0.0.1:8080
loglevel: info

# 🔒 Configuración de seguridad
protocol: quic
retries: 5
grace-period: 30s
